### ISSUE TITLE
How does Window message work?

### ISSUE THREAD

**Issue by kevinrademan** [natevoci/KeyboardRedirector#3]
Can you use the window message to send input directly to a specific window?
Eg. You enter text into notepad, but it get written to sublime?

**Comment by natevoci** [comment]
Maybe. But not easily.

Theoretically you could configure window message actions for every key to send the key to a different window, but it depends on how the target application reads keystrokes. See https://stackoverflow.com/a/39901346 for more explanation.

Even if you could get it to work, you struggle to be able to get it to work with modifiers (Shift, Ctrl, Alt), so you'd be stuck typing in lowercase (or uppercase).

If you want to experiment with it you can get the windows message codes for WM_KEYDOWN etc.. from msdn here https://msdn.microsoft.com/en-us/library/windows/desktop/ms646280(v=vs.85).aspx
and the virtual key codes for the wParam from https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx

**Comment by kevinrademan** [comment]
Ahh ok, I understand what you mean. I've been playing around with the Win32 api and did actually manage to send key strokes to inactive windows.

What I was trying to do (just for fun, not really work related), was create a system where someone could use steam streaming to play a game from my pc while Im using the PC for a different use. 

Theoretically windows has all the pieces to make this work, but getting them to work together is a minefield of complexity ;-)

If I manage to get it working, I'll let you know as you're library helped me understand quite abit of the underlying features I need to use to get this working
